typedef	enum 
{
	FIS_TYPE_REG_H2D		= 0x27,
	FIS_TYPE_REG_D2H		= 0x34,
	FIS_TYPE_DMA_ACT		= 0x39,
	FIS_TYPE_DMA_SETUP		= 0x41,
	FIS_TYPE_DATA 			= 0x46,
	FIS_TYPE_BIST			= 0x58,
	FIS_TYPE_PIO_SETUP		= 0x5F,
	FIS_TYPE_DEV_BETS		= 0xA1
} FIS_TYPE;

