#!/bin/bash
set -e
if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./clean
	. ./headers
else
	. ./config
fi

DESTDIR="$PWD/../sysroot" $MAKE -j $(($(nproc) + 1)) -s -C ../src install