#!/bin/bash
set -e
if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./config
fi

$MAKE -s -C ../src clean

rm -rf ../log
rm -rf ../sysroot
rm -rf ../isodir
rm -rf ../BaMF.iso
rm -rf ../BaMF.vdi
