#!/bin/sh
set -e
if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./config
fi

$MAKE -C ../src clean

rm -rfv ../log
rm -rfv ../sysroot
rm -rfv ../isodir
rm -rfv ../BaMF.iso
rm -rfv ../BaMF.vdi
