#!/bin/sh
export MAKE=${MAKE:-make}
export HOST=${HOST:-$(./default-host)}

export AR=${HOST}-ar
export AS=${HOST}-as
export CC=${HOST}-gcc

export ARCH=${ARCH:-$(./target-triplet-to-arch $(./default-arch))}
export PREFIX=/usr
export EXEC_PREFIX=$PREFIX
export BOOTDIR=/boot
export LIBDIR=$EXEC_PREFIX/lib
export INCLUDEDIR=$PREFIX/include

if [[ "x${HOST}" == "xx86_64-elf" ]]; then
	export CFLAGS='-ffreestanding -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -O2'
else
	export CFLAGS='-O2'
fi

export CPPFLAGS=''

# Configure the cross-compiler to use the desired system root.
export CC="$CC --sysroot=$PWD/../sysroot"

# Work around that the -elf gcc targets doesn't have a system include directory
# because configure received --without-headers rather than --with-sysroot.
if echo "$HOST" | grep -Eq -- '-elf($|-)'; then
  export CC="$CC -isystem=$INCLUDEDIR"
fi
