#!/bin/sh
set -e
. ./build

[[ -d ../isodir ]] && rm -rf ../isodir 
mkdir -p ../isodir
mkdir -p ../isodir/boot
mkdir -p ../isodir/boot/grub

cp ../sysroot/boot/BaMF.kernel ../isodir/boot/BaMF.kernel
cat > ../isodir/boot/grub/grub.cfg << EOF
menuentry "BaMF-OS" {
	multiboot /boot/BaMF.kernel
}
EOF
grub-mkrescue -d /usr/lib/grub/i386-pc/ -o ../BaMF.iso ../isodir
[[ -f ../BaMF.vdi ]] && rm ../BaMF.vdi
VBoxManage convertfromraw ../BaMF.iso ../BaMF.vdi
