#!/bin/sh
set -e
if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./clean
	. ./iso
fi

[ -d ../dist ] || mkdir -p ../dist

mv ../BaMF.iso ../dist/BaMF-$ARCH-$(date -I).iso
mv ../BaMF.vdi ../dist/BaMF-$ARCH-$(date -I).vdi
