#!/bin/sh
set -e

if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./iso
fi

let mem=($(awk '/^MemTotal:/{print $2}' /proc/meminfo)/4096+1023)/1024*1024
qemu-system-i386 -cdrom ../BaMF.iso -m $mem