#!/bin/bash
#set -e
if [[ $# -ge 1 ]]; then
	while [[ "x$1" != "x--no-staging" && $# -ne 0 ]]; do
		shift;
	done
fi
if [[ $# -eq 0 ]]; then
	. ./iso
fi
echo "Running QEMU..."
let mem=($(awk '/^MemTotal:/{print $2}' /proc/meminfo)/4096+1023)/1024*1024;
qemu-system-$(./target-triplet-to-arch $(./default-host)) -curses  -cdrom ../BaMF.iso -m $mem \
-net user,hostfwd=tcp:5555:22 -net nic
echo $?