#!/bin/bash
set -e

for file in `ls ../log/*.c.log`; do

	if [[ "x$file" != "xBaMF.kernel.log" ]]; then
		sed -i -e 's/^.*\/\(.*\) error: \(.*\)/ERR -- \1 <- \2/g' ../log/$file;
		sed -i -e 's/^.*\/\(.*\) warning: \(.*\)/WRN -- \1 <- \2/g' ../log/$file;
		sed -i -e '/<-/!d' ../log/$file;
	else
		sed -i -e 's/^.*\/\(.*\):\([0-9]*\):\(.*\)/LNK -- \1:\2 <- \3/g' ../log/$file;
		sed -i -e '/<-/!d' ../log/$file;
	fi;
done;

find ../log -empty -type f -delete;